### ISSUE TITLE
labeledColsRows breaks with comma in cell

### ISSUE THREAD

**Issue by dmatesic** [giladaya/get-sheet-done#4]
As an example, using `labeledColsRows` on the table:

column1 | column2
--- | ---
a | b, c

returns the following data:

```
{
  a: {
    c: undefined
    column2: "b"
  }
}
```

`labeledCols` works as expected:

```
{
  0: {
    column1: "a"
    column2: "b, c"
  }
}
```

**Comment by giladaya** [comment]
Solved with #5
